### PR TITLE
GitHub actions

### LINKED ISSUE #116: Migrate to travis-ci.com
https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps
https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org

### PR DESCRIPTION
**Pull request by mkuthan**
Voila - project build migrated from Travis to GitHub Actions
closes #116

### CODE REVIEW

**Review by adrianmroz — APPROVED** [review]
Looks great! If it goes green, we can merge and forget travis!

**Comment by adrianmroz** [comment]
I changed branch protection rules, now we require 4 actions to complete and I removed travis requirement. Probably we should in travis remove our repository?

**Comment by mkuthan** [comment]
Green :) I also disabled Turnilo in Travis (or at least I hope so)

**Comment by adrianmroz** [comment]
Wow, after changing branch protection rules, all old PRs spawned actions!

**Comment by mkuthan** [comment]
We'll see quotas on GitHub Actions sooner or later :P

**Pull request merged**
