### PR TITLE
Adding Support for HLL Sketch type

### PR DESCRIPTION
**Pull request by moshederri**
Prior to version 1.17.0, Turnilo failed to discover tables containing HLLSketch types, which eventually caused an incomplete view of the cluster data sources. However, in 1.17.0, those tables are getting discovered and eventually shown, but when an HLLSketch measure is being selected, it will throw an internal server error on the UI, and 'com.yahoo.sketches.hll.HllSketch cannot be cast to java.lang.Number' on the server.

The reason for this behavior is when creating the measure property (name and formula), it falls 
back to doubleSum as HLLSketch is not present.

The proposed solution is to add HLLSketch with the same behavior as hyperUnique.

### CODE REVIEW

**Comment by adrianmroz** [comment]
Thanks for contribution! We don't have bandwidth to check this right now but be patient. I should come back later this week!

**Comment by mkuthan** [comment]
The change looks reasonable. But I'm wondering how it works for us without this change?

Druid query:
```
{
      "queryType": "timeseries",
      "dataSource": "event_raw",
      "intervals": "2019-10-21T14:49Z/2019-10-22T14:49Z",
      "granularity": "all",
      "aggregations": [
        {
          "name": "__VALUE__",
          "type": "HLLSketchMerge",
          "fieldName": "event_client_unique_count_datasketches"
        }
      ]
    }
```

Datasource metric definition:
```
{
"type": "HLLSketchBuild",
"name": "event_client_unique_count_datasketches",
"fieldName": "client_id",
"lgK": 12,
"tgtHllType": "HLL_4"
}
```

And Turnilo config:
```
- name: event_client_unique_count_datasketches
    title: Unique Clients
    formula: $main.countDistinct($event_client_unique_count_datasketches)
    description: |
      Number of unique clients
```

**Comment by moshederri** [comment]
I think the main reason it works for you is that you must update Turnilo config for each HLLSketch* measure added to any of the data sources (same as we had to do using Pivot) which Turnilo discovers. The change I am offering removes the dependency of HLL measures types with Turnilo config.

**Comment by adrianmroz** [comment]
> I'm wondering how it works for us without this change?

> And Turnilo config:
> 
> ```
> - name: event_client_unique_count_datasketches
>     title: Unique Clients
>     formula: $main.countDistinct($event_client_unique_count_datasketches)
>     description: |
>       Number of unique clients
> ```

We define expression in config, so introspection doesn't really run there.

**Comment by adrianmroz** [comment]
@moshederri we will soon release beta version with this fix, we will wait for your confirmation that issue is fixed for you.

**Pull request merged**
