### PR TITLE
Updated to latest node v16

### PR DESCRIPTION
**Pull request by piwysocki**
bump sass-loader

ts-lint update and code cleanup

### CODE REVIEW

**Comment by adrianmroz-allegro** [comment]
Still failing on 16.18 (https://github.com/allegro/turnilo/actions/runs/3500952786/jobs/5868738114).

Nevertheless, I'm very excited at the prospect of bumping all sass related dependencies!

**Comment by piwysocki** [comment]
Sorry, now it should be OK.

**Comment by piwysocki** [comment]
Size workflow should be run with previous node version as it checks current master, will update in next pr. Can you run checks again?

**Comment by piwysocki** [comment]
Do you have any ideas why "Authenticate with GCP" returns: "No authentication found for gcloud"

**Comment by adrianmroz-allegro** [comment]
> Do you have any ideas why "Authenticate with GCP" returns: "No authentication found for gcloud"

I'll just mention @mkuthan ;)

**Comment by adrianmroz-allegro** [comment]
Deploy check is probably failing because we can't create Docker tag for fork repo.
Lighthouse also will probably work from our repository.

One question though, do your changes work only on specified versions? Previously we had "14.x" and "16.x" version declared and it would be great if we could come back to this.

**Comment by piwysocki** [comment]
> Deploy check is probably failing because we can't create Docker tag for fork repo. Lighthouse also will probably work from our repository.
> 
> One question though, do your changes work only on specified versions? Previously we had "14.x" and "16.x" version declared and it would be great if we could come back to this.

My changes work on all versions 14.x and 16.x

**Comment by piwysocki** [comment]
Is this first time when somebody creates a PR from a fork repository?

**Comment by adrianmroz-allegro** [comment]
> My changes work on all versions 14.x and 16.x

So let's switch where possible to "16.x" and "14.x" versions.


> Is this first time when somebody creates a PR from a fork repository?

It could be first PR from fork since we added Deploy, Size and Lighthouse checks :D

**Comment by adrianmroz-allegro** [comment]
Hey, why close? We'd be happy to merge these changes and solve this problem. If you don't have bandwidth for this, we can copy your changes and marge internally.

**Comment by piwysocki** [comment]
I've just opened new PR

**Pull request closed without merging**
