### PR TITLE
fix v2 view definition conversion

### PR DESCRIPTION
**Pull request by itszootime**
The current v2 view definition converter doesn't convert splits and filters using time or dimensions with lookups, fallbacks, etc. properly. The idea behind this fix is to lookup the dimension using the parsed expression (i.e. the `formula` defined in the config), rather than name.

For context, we're currently using https://github.com/yahoo/swiv at the latest master and would like to transition to Turnilo without breaking existing links.

I left two comments in the code where I wasn't sure if they were bugs (e.g. using `bucketAction.op` instead of `bucketAction.action`), so I kept support for both cases.

### CODE REVIEW

**Comment by adrianmroz** [comment]
I don’t understand why matching dimensions using expression. Could you elaborate/provide counterexample?

**Comment by itszootime** [comment]
Sure. Consider, for example, that data cube configuration contains the following "dimension"

```
- name: page_last_author
   title: Page Author
   formula: $page.lookup(page_last_author)
```

`page_last_author` doesn't actually exist in  as a dimension in Druid, it's a lookup using the `page` dimension. If you include a split on this in Pivot/swiv, the view definition will contain

```
splits: [
  {
    expression: {
      op: "chain",
      expression: {
        op: "ref",
        name: "page"
      },
      actions: [
        {
          action: "lookup",
          lookup: "page_last_author"
        }
      ]
    },
    sortAction: {
      action: "sort",
      expression: {
        op: "ref",
        name: "count"
      },
      direction: "descending"
    },
    limitAction: {
      action: "limit",
      limit: 10
    }
  }
]
```

When trying to convert the split, the line

```
const reference = (expression as RefExpression).name;
```

is falsely assuming that every split expression will be a `RefExpression` and returns `undefined` for this case. Therefore, the only reliable method to find the Turnilo "dimension" name from this view definition version is to use the `getDimensionByExpression` function.

**Comment by itszootime** [comment]
Linting issues have been resolved.

**Comment by itszootime** [comment]
swiv is using a private fork `swiv-plywood@0.12.17`. I found some relevant information from the changelog regarding `limit`:

From 0.14.1

> changed `LimitAction#limit` to `LimitExpression#value`

**Comment by adrianmroz** [comment]
Great catch. We need to confirm all differences and put them in code explicitly. I’ll validate our fixtures and old links tomorrow.

**Comment by adrianmroz** [comment]
Few things:

1. There's bug on master with v2 conversion of RelativeTimeFilter. We will fix it and it should simplify your PR.
2. Due to changes in plywood, matching dimensions by expression is brittle. We can't guarantee anything there.
3. We should extract methods that read plywood objects so they could handle multiple versions. First - limit `value` vs `limit` and generally, old plywood used `action` field on `Action`, now it uses `op`.

**Comment by adrianmroz** [comment]
Ad. 3 I was thinking about two functions - `isBucketAction` and `limitValue`. 

Ad. 1 I will create PR with fix later today. Good news is, that this is identical to your changes :)

**Comment by adrianmroz** [comment]
Please check #266.

**Comment by itszootime** [comment]
@adrianmroz rebased against master, let me know if there's anything more than needs to be done here.

**Pull request merged**
