### PR TITLE
line chart hover indicators

### LINKED ISSUE #403: Enhancement: Link display values between multiple charts
It would be helpful to display all charts value at some point in time when mouse-move over a single chart. As an example, [have a look here](http://www.tylernwolf.com/legacy/#/portfolio/corrdisp).
Following the screenshot from the actual line charts view: 
image
an idea would be display `hoverInfo` for all charts instead of single one. Also an extra vertical line could be added (between chart graphics and hover info) if not much work to do (I guess a charts wrapper would be required).

### PR DESCRIPTION
**Pull request by adrianmroz**
Closes #403

### CODE REVIEW

**Comment by alexbusu** [comment]
Great job, @adrianmroz ! Now, as I test this branch I agree - maybe the vertical lines are too much, since there are the hover points as well...

**Comment by alexbusu** [comment]
There are some issues I experiment with this PR changes.
image
1. The tooltip position is too far from mouse position.
image
2. On the left edge the tooltip doesn't switch position relative to mouse, and gets hidden.
image
3. Selecting more than 2 measures will break tooltip style and vertical position.

To open new issue?

**Comment by adrianmroz** [comment]
Sure do! You're testing from master? What browser?

**Comment by alexbusu** [comment]
I'm testing from the merged branch (checked-out last Friday). I did not know when the last addition will be done into this PR, so I hold on to comment earlier...
Google Chrome is the browser.
I just tested from master - it the same issue.
Ok, I'll add the issue. Thank you!

**Pull request merged**
