### PR TITLE
Run precalculate before setting datasetLoad

### LINKED ISSUE #278: Bar Chart crash
Turnilo crashed when I selected the Bar Chart view, I'm using current master with the 12-hour clock patch (a352cc674f9ddda6e448d42e1baa835c6871defc).

```
TypeError: maxNumberOfLeaves is undefined bar-chart.tsx:816:10
	BarChart.prototype.getXValues bar-chart.tsx:816:10
	BarChart.prototype.getPrimaryXScale bar-chart.tsx:796:10
	BarChart.prototype.renderInternals bar-chart.tsx:937:21
	BaseVisualization.prototype.render base-visualization.tsx:151:32
	finishClassComponent react-dom.development.js:7873
	updateClassComponent react-dom.development.js:7850
	beginWork react-dom.development.js:8225
	performUnitOfWork react-dom.development.js:10224
	workLoop react-dom.development.js:10288
	callCallback react-dom.development.js:542
	invokeGuardedCallbackDev react-dom.development.js:581
	invokeGuardedCallback react-dom.development.js:438
	renderRoot react-dom.development.js:10366
	performWorkOnRoot react-dom.development.js:11014
	performWork react-dom.development.js:10967
	requestWork react-dom.development.js:10878
	scheduleWorkImpl react-dom.development.js:10732
	scheduleWork react-dom.development.js:10689
	enqueueSetState react-dom.development.js:6212
	Component.prototype.setState react.development.js:237
	BaseVisualization.prototype.handleDatasetLoad base-visualization.tsx:112:4
	BaseVisualization/_this.callExecutor/< base-visualization.tsx:97:10
	_fulfilled q.js:854
	Promise.prototype.then/</< q.js:883
	Promise/promise.promiseDispatch q.js:816
	become/</< q.js:624
	runSingle q.js:137
	flush q.js:125
	run setImmediate.js:40
	runIfPresent setImmediate.js:69
	onGlobalMessage setImmediate.js:109
```

### PR DESCRIPTION
**Pull request by l2dy**
Closes #278.

### CODE REVIEW

**Comment by l2dy** [comment]
Related code introduced in #268.

**Comment by adrianmroz** [comment]
Ok, I see the problem that I introduced here. Before, there was one `setState` caused by promise fulfilment. Now we have two - one in `BaseVisualization` and optionally one in `precalculate`. 

I see two options:
1. `precalculate` could return state chunk and `BaseVisualization` will set it with `dataset`. It will more tightly couple child with parent and probably introduce new state typing issues.
2. pick an order and ensure that rendering is robust - it can handle cases where for example `dataset` is present but not calculated state. It's hard to enforce such contract in code.

_train of thoughts starts here_
I would prefer second version. By the way, `precalculate` is bad name here. Maybe `deriveState`? `calculateDerivedState`?

Because `precalculate` is not guaranteed to be called after state is modified by React, we need to pass dataset explicitly. We need to be cautious with using `setState` with object param - to not override `handleDatasetLoad` changes.

If we run precalculate later but set default state such that renders passes we could fix that. But next case is - what if we load new dataset - we run render with old precalculations and new dataset. Will it break? Maybe first version with synchronising state changes is valid? 

Or am I overthinking it, and even if React tries renders something with inconsistent dataset-precalculate it will happen for one frame or so, and probably wouldn't be even flushed to browser?

**Comment by adrianmroz** [comment]
I implemented quick version of 1 in #282 What do you think?

**Comment by l2dy** [comment]
> I implemented quick version of 1 in #282 What do you think?

I'm not sure which way is better, but your PR did fix the crash ;)

**Comment by adrianmroz** [comment]
I think precalculate as pure function will work better. One async operation is better than two. Anyway, thanks for guiding me to place where error was!

**Pull request closed without merging**
