### PR TITLE
Add TypeScript compiler test

### PR DESCRIPTION
**Pull request by l2dy**

### CODE REVIEW

**Comment by adrianmroz** [comment]
I agree with the problem, but I don't think it's that easy.

We get errors from tsc, because there are some errors in files that are unused in project. In all used files, typescript fill wind errors during build (for server and client) and during test for test files. If file is not used, tic will not reach to it.

Adding just tsc to travis is problematic - we should ensure that such compilation step won't produce any artifacts and it's downside is that it takes time and really, you're compiling 90% of files second time.

Finding unused files is something for linter, but I'm not aware of any reasonable solutions for that. 

Bright side is - those errors don't affect application in any way. If you import such incorrect file in app or test, typescript will reach it and report error.

**Comment by l2dy** [comment]
> I agree with the problem, but I don't think it's that easy.
> 
> We get errors from tsc, because there are some errors in files that are unused in project. In all used files, typescript fill wind errors during build (for server and client) and during test for test files. If file is not used, tic will not reach to it.
> 
> Adding just tsc to travis is problematic - we should ensure that such compilation step won't produce any artifacts and it's downside is that it takes time and really, you're compiling 90% of files second time.

As the last step in Travis CI testing, I don't think producing artifacts would matter. The build machine would be destroyed afterwards.

**Comment by l2dy** [comment]
> I agree with the problem, but I don't think it's that easy.
> 
> We get errors from tsc, because there are some errors in files that are unused in project. In all used files, typescript fill wind errors during build (for server and client) and during test for test files. If file is not used, tic will not reach to it.
> 
> Adding just tsc to travis is problematic - we should ensure that such compilation step won't produce any artifacts and it's downside is that it takes time and really, you're compiling 90% of files second time.
> 
> Finding unused files is something for linter, but I'm not aware of any reasonable solutions for that.
> 
> Bright side is - those errors don't affect application in any way. If you import such incorrect file in app or test, typescript will reach it and report error.

`HighlightFixtures` is used in the `describe("removes highlight when necessary", ...` test in essence.mocha.ts, but the type errors in #309 was not reported. Any idea how that happened?

**Comment by adrianmroz** [comment]
Huh, that's interesting. I assumed `ts-node/register` in mocha setup handles that. Maybe it's not full blown transpilation? I will investigate that further. 

But that looks like we have only guarantee about correctness of tests, not accordance with typescript.

**Comment by adrianmroz** [comment]
`ts-node` by default only transpires ts to js. I enabled type-checking in #310

**Comment by l2dy** [comment]
> `ts-node` by default only transpires ts to js. I enabled type-checking in #310

It works and is a better solution, so I'm closing this one.

**Comment by adrianmroz** [comment]
There's still case like that with filters.fixture, but I don't know how to solve it nicely. And it has virtually zero impact.

**Pull request closed without merging**
