### PR TITLE
Create lazy getter for DataSetWithTabOptions in cube-view

### PR DESCRIPTION
**Pull request by adrianmroz**

### CODE REVIEW

**Comment by adrianmroz** [comment]
Let's merge it as temporary solution for #536

**Comment by adrianmroz** [comment]
Check scenario: full reload, _viz registers downloadable dataset_, click on share menu, check if everything is wired correctly e.g. if file downloads

**Comment by adrianmroz-allegro** [comment]
Lets kill this PR. We should lift `dataset` from `BaseVisualisation` to `CubeView` so we don't need to "register" datasets. It is unwieldy. We would need some small change to visualisations. Lets drop "derivedState" and just memoize this transformation inside component. So when new dataset comes to visualisation, it can call this transformation and get derived dataset.

**Comment by adrianmroz** [comment]
Just testing subs

**Pull request closed without merging**
