### PR TITLE
Fix creating fixed time short URL

### PR DESCRIPTION
**Pull request by l2dy**
`specificHash` is converted to fixed time, `hash` is not.

https://github.com/allegro/turnilo/blob/1802e4c14d26cc9b9abc93762211fb6db6d07796/src/client/components/share-menu/share-menu.tsx#L70-L71

https://github.com/allegro/turnilo/blob/1802e4c14d26cc9b9abc93762211fb6db6d07796/src/client/components/share-menu/share-menu.tsx#L84-L88

### CODE REVIEW

**Comment by l2dy** [comment]
Good to merge? @adrianmroz

**Comment by adrianmroz** [comment]
We're running beta with quantile measures right now. Your PR shouldn't influence measures code but you never know. We will merge it after the beta or right in next version which would be mostly technical. So I would ask for your patience :)

**Comment by l2dy** [comment]
OK. I hope it won't be delayed to the next release though. It's a really simple bug fix after all.

**Comment by l2dy** [comment]
Thanks for merging!

**Pull request merged**
